// Grovetown SEO demand surfaces: the "Popular Grovetown pickups" homepage section,
// the Grovetown demand pages generated by the factory (mattress/furniture/appliance/
// bulk), the lead-form readability fix, and the success confirmation copy.
//
// Banned-claim coverage for the new niche/content text is enforced globally by
// tests/copy/compliance.test.ts (lib/seo/niches.ts and lib/seo/content.ts are in its
// COPY_FILES list); this file adds the Grovetown-specific prohibitions called out for
// these pages (fixed prices, same-day promises, Freon/refrigerant promises, on-post /
// official-military claims, reviews, licenses, and municipal trash-rule claims).

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

import {
  resolveSlug,
  getPublishedSlugs,
  getAllStaticSlugs,
  getPageBySlug,
  getPagesForCity,
} from "../../lib/seo";
import { buildServiceSchema, buildFaqSchema } from "../../lib/seo/schema";

const ROOT = process.cwd();
const read = (rel: string) => fs.readFileSync(path.join(ROOT, rel), "utf8");

const MATTRESS = "mattress-removal-grovetown-ga";
const DEMAND_PAGES = [
  "mattress-removal-grovetown-ga",
  "furniture-removal-grovetown-ga",
  "appliance-removal-grovetown-ga",
  "bulk-item-pickup-grovetown-ga",
];

// ── Homepage: "Popular Grovetown pickups" ────────────────────────────────────

test("homepage has a visible Popular Grovetown Pickups section", () => {
  const home = read("app/page.tsx");
  assert.ok(/Popular Grovetown Pickups/.test(home), "homepage shows the section heading");
  // Keeps the Grovetown / Fort Eisenhower-area / PCS positioning.
  assert.ok(/fort eisenhower/i.test(home), "section keeps Fort Eisenhower-area positioning");
  assert.ok(/\bPCS\b/.test(home), "section keeps PCS positioning");
});

test("homepage lists the requested Grovetown pickup item types", () => {
  const home = read("app/page.tsx");
  const items = [
    "Mattress & box spring pickup",
    "Couch, sofa & furniture pickup",
    "Washer & dryer removal",
    "Large appliance pickup",
    "Bulk item pickup",
    "Rental cleanouts",
    "Tenant trash-outs",
    "Carpet & padding removal",
  ];
  for (const label of items) {
    assert.ok(home.includes(label), `homepage lists "${label}"`);
  }
});

test("homepage Popular Pickups links point at published Grovetown pages", () => {
  const home = read("app/page.tsx");
  const published = new Set(getPublishedSlugs());
  for (const slug of DEMAND_PAGES) {
    assert.ok(home.includes(`/${slug}`), `homepage links to /${slug}`);
    assert.ok(published.has(slug), `/${slug} is published (won't 404)`);
  }
  // The rental/tenant Grovetown pages and the carpet hub the section links to also exist.
  assert.ok(published.has("rental-property-cleanout-grovetown-ga"));
  assert.ok(published.has("tenant-trash-out-grovetown-ga"));
  assert.ok(resolveSlug("carpet-removal")?.kind === "niche", "carpet-removal hub resolves");
});

// ── Factory: the Grovetown demand pages are generated ────────────────────────

test("the four Grovetown demand pages resolve to published landing pages", () => {
  for (const slug of DEMAND_PAGES) {
    const resolved = resolveSlug(slug);
    assert.ok(resolved, `${slug} resolves`);
    assert.equal(resolved!.kind, "page", `${slug} is a niche×city landing page`);
  }
});

test("each new niche also generates a static niche hub", () => {
  const all = new Set(getAllStaticSlugs());
  for (const hub of ["mattress-removal", "furniture-removal", "appliance-removal", "bulk-item-pickup"]) {
    assert.ok(all.has(hub), `niche hub /${hub} is statically generated`);
  }
});

// ── The flagship mattress page has every required SEO element ─────────────────

test("mattress-removal-grovetown-ga has title, description, H1, intro, FAQs, and schema", () => {
  const page = getPageBySlug(MATTRESS);
  assert.ok(page, "mattress Grovetown page is published");
  const { niche, city, content, faqs } = page!;

  const title = niche.metaTitle(city.name, city.state);
  const desc = niche.metaDescription(city.name, city.state);
  const h1 = niche.h1(city.name, city.state);

  assert.match(title, /Mattress/i, "SEO title names the service");
  assert.ok(desc.length >= 80, "meta description is substantial");
  assert.match(h1, /Mattress/i, "H1 names the service");
  assert.match(h1, /Grovetown/, "H1 names the city");

  // Strong, city-specific intro (publish gate is 80 chars; demand copy is well over).
  assert.ok(content.intro.length >= 200, "intro is a real, local paragraph");
  assert.match(content.intro, /Grovetown/);

  // Niche-level + ≥1 city-specific FAQ merged.
  assert.ok(faqs.length >= 5, "page carries a full FAQ set");

  // Positioning requirements for the mattress page.
  const allText = [content.intro, niche.overview(city.name), ...faqs.map((f) => `${f.q} ${f.a}`)].join(" ");
  assert.match(allText, /curbside|driveway/i, "encourages curbside/driveway pickup");
  assert.match(allText, /indoor|inside|upstairs/i, "notes indoor removal is by quote");
  assert.match(allText, /\bPCS\b/, "calls out PCS moves");
  assert.match(allText, /photo/i, "offers a quote from photos");

  // Structured data builders produce valid Service + FAQ schema.
  const serviceSchema = buildServiceSchema(page!) as { "@type": string };
  assert.equal(serviceSchema["@type"], "Service");
  const faqSchema = buildFaqSchema(faqs) as { "@type": string; mainEntity: unknown[] };
  assert.equal(faqSchema["@type"], "FAQPage");
  assert.equal(faqSchema.mainEntity.length, faqs.length);
});

test("the Grovetown demand pages are internally linked via the city mesh", () => {
  const grovetownSlugs = new Set(getPagesForCity("grovetown-ga").map((p) => p.slug));
  for (const slug of DEMAND_PAGES) {
    assert.ok(grovetownSlugs.has(slug), `${slug} is in the Grovetown city hub / internal-link mesh`);
  }
  // The landing-page template drives every page's primary CTA to the lead form.
  assert.ok(read("components/seo/LandingPage.tsx").includes("/leads/new"), "landing page CTA targets /leads/new");
});

// ── No banned claims on the new Grovetown surfaces ───────────────────────────

test("new niche/content copy makes no banned Grovetown claims", () => {
  const files = ["lib/seo/niches.ts", "lib/seo/content.ts", "app/page.tsx"];
  const banned: { label: string; re: RegExp }[] = [
    { label: "fixed price / price range", re: /\$\s?\d/ },
    { label: "same-day / next-day promise", re: /\bsame[\s-]?day\b|\bnext[\s-]?day\b/i },
    { label: "Freon claim", re: /\bfreon\b/i },
    { label: "refrigerant-work promise", re: /\brefrigerant (?:removal|recovery|disposal) (?:is )?included\b/i },
    { label: "on-post / on-base service", re: /\bon[\s-]?post\b|\bon[\s-]?base\b/i },
    { label: "official military partnership / endorsement", re: /\bofficial(?:ly)?\s+military\b|\bmilitary\s+partner(?:ship)?\b|\bendorsed by\b|\baffiliated with\b/i },
    { label: "rating / review claim", re: /\b5[\s-]?star\b|\bfive[\s-]?star\b|\bstar[\s-]?rated\b|\bhappy customers\b|\btrusted by\b/i },
    { label: "license / insurance / guarantee claim", re: /\blicensed (?:and|&) insured\b|\bfully (?:licensed|insured)\b|\bguarantee/i },
    { label: "municipal / city trash-rule claim", re: /\bmunicipal\b|\bcity (?:trash|garbage|bulk|bulky) (?:rules?|pickup|schedule|day)\b/i },
  ];
  for (const rel of files) {
    const text = read(rel);
    for (const { label, re } of banned) {
      assert.equal(text.match(re), null, `${rel} contains banned wording (${label}): ${JSON.stringify(text.match(re)?.[0])}`);
    }
  }
});

// ── Lead form: readability + success confirmation ────────────────────────────

test("the request form's service select and inputs have readable, explicit colors", () => {
  const form = read("app/leads/new/LeadForm.tsx");
  // inputCls (the service <select>, text inputs, and textarea) sets an explicit light
  // background and dark text so it stays readable under a dark OS color scheme.
  assert.match(form, /const inputCls\s*=\s*[\s\S]*?bg-white[\s\S]*?text-gray-900/, "inputCls forces bg-white + dark text");
  // The pickup-location option cards are readable in unselected, selected, hover, and
  // focus states.
  const unselectedCard = /border-gray-200 bg-white[^"]*hover:bg-gray-50/;
  assert.match(form, unselectedCard, "unselected cards have a light background + hover");
  assert.ok(form.includes("focus-within:ring-2"), "cards show a visible focus ring");
  assert.ok(form.includes('"text-green-800"') || form.includes("text-green-800"), "selected card text stays dark on the green fill");
});

test("the success screen shows the request-received confirmation copy", () => {
  const form = read("app/leads/new/LeadForm.tsx");
  assert.match(form, /Request received/, "confirms the request was received");
  assert.match(form, /review your photos and details/, "tells the customer we'll review photos/details");
  assert.match(form, /send you a quote/, "tells the customer a quote is coming");
});
